"""Добавил 2 модели(Character, UserCharacter) + логика при создании персонажа

Revision ID: 6936e0ce9910
Revises: 5115942acc05
Create Date: 2024-05-15 00:27:53.928028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6936e0ce9910'
down_revision: Union[str, None] = '5115942acc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Float(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('intellect', sa.Integer(), nullable=True),
    sa.Column('class_', sa.Enum('Warrior', 'Mage', 'Archer', name='class_enum'), nullable=True),
    sa.Column('race', sa.Enum('Human', 'Elf', 'Dwarf', 'Orc', name='race_enum'), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('_mana', sa.Float(), nullable=True),
    sa.Column('_abilities', sa.Enum('Fireball', 'Heal', 'Stealth', 'Double Strike', name='abilities_enum'), nullable=True),
    sa.Column('history', sa.String(), nullable=True),
    sa.Column('faction', sa.Enum('Alliance', 'Horde', name='faction_enum'), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('user_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_characters_id'), 'user_characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_characters_id'), table_name='user_characters')
    op.drop_table('user_characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
