"""Обновил модель haracter

Revision ID: 7ce9ab1f1b81
Revises: 6936e0ce9910
Create Date: 2024-05-16 22:44:30.155445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce9ab1f1b81'
down_revision: Union[str, None] = '6936e0ce9910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('mana', sa.Float(), nullable=True))
    op.add_column('characters', sa.Column('abilities', sa.Enum('Fireball', 'Heal', 'Stealth', 'Double Strike', name='abilities_enum'), nullable=True))
    op.drop_column('characters', '_abilities')
    op.drop_column('characters', '_mana')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('_mana', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('_abilities', postgresql.ENUM('Fireball', 'Heal', 'Stealth', 'Double Strike', name='abilities_enum'), autoincrement=False, nullable=True))
    op.drop_column('characters', 'abilities')
    op.drop_column('characters', 'mana')
    # ### end Alembic commands ###
